import { useState } from 'react'
import type { FormEvent } from 'react'
import { Link, useNavigate, useOutletContext } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { orderApi } from '../../../entities/order'
import { userApi } from '../../../entities/user'
import type { User } from '../../../entities/user'
import { date, money } from '../../../shared/lib/format'
import { Button } from '../../../shared/ui/Button'

export function AccountPage() {
  const user = useOutletContext<User>()
  const client = useQueryClient()
  const navigate = useNavigate()
  const [confirmDelete, setConfirmDelete] = useState(false)
  const [passwordMismatch, setPasswordMismatch] = useState(false)
  const orders = useQuery({ queryKey: ['orders', 0], queryFn: () => orderApi.list(0) })
  const update = useMutation({ mutationFn: userApi.update, onSuccess: (value) => { client.setQueryData(['user'], value); client.setQueryData(['account'], value) } })
  const password = useMutation({ mutationFn: userApi.password, onSuccess: () => { client.clear(); navigate('/login', { replace: true }) } })
  const deactivate = useMutation({ mutationFn: userApi.deactivate, onSuccess: () => { client.clear(); navigate('/', { replace: true }) } })
  function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); update.mutate({ full_name: String(values.get('full_name')).trim() || null, username: String(values.get('username')).trim(), email: String(values.get('email')).trim() }) }
  function savePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); const next = String(values.get('new_password')); if (next !== values.get('confirm_password')) { password.reset(); setPasswordMismatch(true); return } setPasswordMismatch(false); password.mutate({ current_password: String(values.get('current_password')), new_password: next }) }
  return <div><section><h2 className="font-display text-3xl tracking-tight">Мой профиль</h2><form key={user.id + user.updated_at} onSubmit={saveProfile} className="mt-6"><div className="grid gap-5 sm:grid-cols-2"><label><span className="field-label">Имя</span><input name="full_name" className="field" maxLength={128} defaultValue={user.full_name || ''} autoComplete="name" /></label><label><span className="field-label">Имя пользователя *</span><input name="username" required minLength={3} maxLength={32} className="field" defaultValue={user.username} autoComplete="username" /></label><label className="sm:col-span-2"><span className="field-label">Email *</span><input name="email" required type="email" className="field" defaultValue={user.email} autoComplete="email" /></label></div><div className="mt-5 flex items-center gap-4"><Button type="submit" disabled={update.isPending}>{update.isPending ? 'Сохраняем...' : 'Сохранить изменения'}</Button>{update.isSuccess && <span role="status" className="text-xs text-[#458052]">Изменения сохранены</span>}</div>{update.isError && <p role="alert" className="mt-3 text-sm text-red-700">{update.error.message}</p>}</form></section>
    <section className="mt-10 border-t border-line pt-8"><h2 className="font-display text-3xl tracking-tight">Сменить пароль</h2><form onSubmit={savePassword} className="mt-6"><div className="grid gap-5 sm:grid-cols-3"><label><span className="field-label">Текущий пароль *</span><input name="current_password" type="password" required className="field" autoComplete="current-password" /></label><label><span className="field-label">Новый пароль *</span><input name="new_password" type="password" required minLength={8} maxLength={72} className="field" autoComplete="new-password" /></label><label><span className="field-label">Повторите пароль *</span><input name="confirm_password" type="password" required minLength={8} className="field" autoComplete="new-password" /></label></div><Button type="submit" disabled={password.isPending} className="mt-5">Сохранить пароль</Button>{passwordMismatch && <p role="alert" className="mt-3 text-sm text-red-700">Новые пароли не совпадают.</p>}{password.isError && <p role="alert" className="mt-3 text-sm text-red-700">{password.error.message}</p>}</form></section>
    <section className="mt-10 border-t border-line pt-8"><div className="flex items-end justify-between"><h2 className="font-display text-3xl tracking-tight">Мои заказы</h2><Link to="/account/orders" className="text-xs underline underline-offset-4">Смотреть все</Link></div>{orders.data?.items.length ? <div className="mt-5 divide-y divide-line border-y border-line">{orders.data.items.slice(0, 3).map((order) => <Link key={order.id} to={`/account/orders/${order.id}`} className="grid gap-2 py-4 text-xs hover:bg-mist sm:grid-cols-[1fr_1fr_1fr_auto]"><span>№ {order.id.slice(0, 8).toUpperCase()}</span><span className="text-muted">{date(order.created_at)}</span><span>Заказ оформлен</span><strong>{money(order.total)}</strong></Link>)}</div> : <p className="mt-5 text-sm text-muted">Заказов пока нет.</p>}</section>
    <section className="mt-10 border-t border-line pt-8"><h2 className="text-sm font-medium">Удалить аккаунт</h2><p className="mt-2 max-w-lg text-xs leading-5 text-muted">Аккаунт будет отключён, и вход в него станет недоступен.</p><button type="button" onClick={() => setConfirmDelete(true)} className="mt-4 text-xs text-red-700 underline underline-offset-4">Отключить аккаунт</button></section>
    {confirmDelete && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="delete-title" className="w-full max-w-md bg-white p-8 shadow-panel"><h2 id="delete-title" className="font-display text-3xl">Отключить аккаунт?</h2><p className="mt-3 text-sm text-muted">После подтверждения вы выйдете из аккаунта.</p><div className="mt-7 flex flex-wrap gap-3"><Button variant="outline" onClick={() => setConfirmDelete(false)}>Отмена</Button><Button onClick={() => deactivate.mutate()} disabled={deactivate.isPending}>{deactivate.isPending ? 'Отключаем...' : 'Подтвердить'}</Button></div>{deactivate.isError && <p role="alert" className="mt-3 text-sm text-red-700">{deactivate.error.message}</p>}</div></div>}
  </div>
}
