import { Link, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { orderApi, orderStatusLabels } from '../../../entities/order'
import { date, money } from '../../../shared/lib/format'
import { ErrorState, Loading } from '../../../shared/ui/States'

export function OrderDetailsPage({ confirmed = false }: { confirmed?: boolean }) {
  const { id = '' } = useParams()
  const { data: order, error, isPending, refetch } = useQuery({ queryKey: ['order', id], queryFn: () => orderApi.detail(id) })
  if (isPending) return <Loading />
  if (error || !order) return <ErrorState error={error} retry={() => refetch()} />
  return <div className={confirmed ? 'page-container pt-10' : ''}>{confirmed && <p className="mb-3 text-sm text-[#458052]">✓ Заказ успешно оформлен</p>}<h1 className="font-display text-[42px] leading-none tracking-[-.05em]">Заказ № {order.id.slice(0, 8).toUpperCase()}</h1><p className="mt-3 text-sm text-muted">{date(order.created_at)} · Статус: {orderStatusLabels[order.status].toLowerCase()}</p><div className="mt-8 grid gap-10 lg:grid-cols-[minmax(0,1fr)_320px]"><div className="divide-y divide-line border-t border-line">{order.items.map((item) => <div key={item.id} className="flex gap-4 py-5"><div className="h-28 w-[90px] shrink-0 bg-mist">{item.image_url && <img src={item.image_url} alt={item.name} className="h-full w-full object-cover" />}</div><div className="flex-1"><p className="text-sm">{item.name}</p><p className="mt-2 text-xs text-muted">{Object.entries(item.options).map(([key, value]) => `${key === 'size' ? 'Размер' : key}: ${value}`).join(' · ')}</p><p className="mt-2 text-xs text-muted">{item.quantity} шт.</p></div><strong className="text-sm">{money(item.total)}</strong></div>)}</div><aside className="h-fit bg-mist p-6"><h2 className="font-display text-2xl">Детали заказа</h2><p className="mt-5 text-xs text-muted">Получатель</p><p className="mt-1 text-sm">{order.full_name}<br />{order.phone}</p><p className="mt-5 text-xs text-muted">Адрес доставки</p><p className="mt-1 text-sm">{order.city}, {order.address}{order.postal_code ? `, ${order.postal_code}` : ''}</p><p className="mt-5 text-xs text-muted">Оплата при получении · доставка бесплатно</p><div className="mt-5 flex justify-between border-t border-line pt-5 font-medium"><span>Итого</span><span>{money(order.total)}</span></div></aside></div>{confirmed && <div className="mt-9 flex gap-5 text-sm"><Link to="/account/orders" className="underline underline-offset-4">Все заказы</Link><Link to="/catalog" className="underline underline-offset-4">Продолжить покупки</Link></div>}</div>
}
