import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, ArrowRight, Minus, Plus, X } from 'lucide-react'
import { cartApi } from '../../../entities/cart'
import type { CartItem } from '../../../entities/cart'
import { userApi } from '../../../entities/user'
import { money } from '../../../shared/lib/format'
import { EmptyState, ErrorState, Loading } from '../../../shared/ui/States'

function CartRow({ item }: { item: CartItem }) {
  const client = useQueryClient()
  const quantity = useMutation({ mutationFn: (value: number) => cartApi.quantity(item.id, value), onSuccess: (cart) => client.setQueryData(['cart'], cart) })
  const remove = useMutation({ mutationFn: () => cartApi.remove(item.id), onSuccess: (cart) => client.setQueryData(['cart'], cart) })
  return <div className="grid grid-cols-[96px_minmax(0,1fr)] gap-4 border-t border-line py-6 sm:grid-cols-[120px_minmax(0,1fr)_auto] sm:gap-6"><Link to={`/products/${item.slug}`} className="aspect-[4/5] overflow-hidden bg-mist">{item.image_url && <img src={item.image_url} alt={item.name} className="h-full w-full object-cover" />}</Link><div className="min-w-0"><Link to={`/products/${item.slug}`} className="text-sm font-medium hover:underline">{item.name}</Link><p className="mt-2 text-xs text-muted">Артикул: {item.sku}</p>{Object.entries(item.options).map(([key, value]) => <p key={key} className="mt-1 text-xs text-muted">{key === 'size' ? 'Размер' : key}: {value}</p>)}<div className="mt-4 flex items-center gap-3"><div className="flex h-9 items-center border border-line"><button type="button" aria-label="Уменьшить количество" disabled={item.quantity <= 1 || quantity.isPending} onClick={() => quantity.mutate(item.quantity - 1)} className="px-2 disabled:opacity-30"><Minus size={13} /></button><span className="min-w-7 text-center text-xs">{item.quantity}</span><button type="button" aria-label="Увеличить количество" disabled={item.quantity >= item.stock || quantity.isPending} onClick={() => quantity.mutate(item.quantity + 1)} className="px-2 disabled:opacity-30"><Plus size={13} /></button></div><button type="button" onClick={() => remove.mutate()} disabled={remove.isPending} className="flex items-center gap-1 text-xs text-muted hover:text-ink"><X size={14} /> Удалить</button></div>{!item.available && <p className="mt-3 text-xs text-red-700">Количество или наличие изменилось. Обновите корзину.</p>}{quantity.isError && <p role="alert" className="mt-2 text-xs text-red-700">{quantity.error.message}</p>}{remove.isError && <p role="alert" className="mt-2 text-xs text-red-700">{remove.error.message}</p>}</div><div className="col-start-2 self-start text-sm font-semibold sm:col-start-3">{money(item.total, item.currency)}</div></div>
}

export function CartPage() {
  const session = useQuery({ queryKey: ['user'], queryFn: userApi.session, retry: false })
  const { data, error, isPending, refetch } = useQuery({ queryKey: ['cart'], queryFn: cartApi.read, enabled: !session.isPending })
  if (isPending) return <Loading />
  if (error) return <ErrorState error={error} retry={() => refetch()} />
  return <div className="page-container pt-9"><h1 className="display-title">Корзина</h1>{!data?.items.length ? <EmptyState title="Корзина пуста" body="Добавьте вещи, которые хочется взять с собой." /> : <><p className="mt-3 text-sm text-muted">{data.count} товаров на сумму {money(data.total)}</p><div className="mt-9 grid gap-10 lg:grid-cols-[minmax(0,1fr)_340px]"><div><div className="hidden grid-cols-[120px_minmax(0,1fr)_auto] gap-6 pb-4 text-xs text-muted sm:grid"><span>Товар</span><span>Описание</span><span>Сумма</span></div>{data.items.map((item) => <CartRow key={item.id} item={item} />)}<Link to="/catalog" className="mt-7 inline-flex items-center gap-2 text-sm hover:underline"><ArrowLeft size={16} /> Продолжить покупки</Link></div><aside className="h-fit bg-mist p-6 sm:p-8 lg:sticky lg:top-24"><h2 className="font-display text-2xl">Ваш заказ</h2><div className="mt-7 flex justify-between border-b border-[#dedee0] pb-5 text-sm text-muted"><span>Товары ({data.count})</span><span>{money(data.total)}</span></div><div className="my-5 flex justify-between text-base font-semibold"><span>Итого</span><span>{money(data.total)}</span></div><p className="mb-5 text-xs text-muted">Доставка бесплатно · оплата при получении</p><Link to="/checkout" aria-disabled={data.items.some((item) => !item.available)} className={`flex min-h-12 items-center justify-center gap-2 bg-ink px-5 text-sm text-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-tactile ${data.items.some((item) => !item.available) ? 'pointer-events-none opacity-50' : ''}`}>Оформить заказ <ArrowRight size={16} /></Link></aside></div></>}</div>
}
